# This is a workflow that is able to create temporary urls for the test cases and dataset files.
# Trigger: Input cross check completed successfully. 
# Input: The directory path of a test case or dataset file. 
# Output: Four urls that are needed for a test case: 1. the test case url, 2. the corresponding dataset url, 3. the ontology url, 4. The OWL ontology url.

# The name of the workflow
name: Construct OWLUnit test cases

# The event that triggers the action.
on: 
  push: 
    branches: 
      - main
    paths: 
      - 'ontology-network/musical-performance/**'
  workflow_dispatch:

jobs:

# This workflow contains a job called "build-test"
  build-test:
  
  # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Use checkout
        uses: actions/checkout@v2
        
      - name: Input crosscheck
        run: |
            cd ontology-network
            cd musical-performance
            while read -r line; do
            line="$line"
            cd $line
            counter=0
            for file in *.txt
            do 
              if [ -s $file ] 
              then
                rm -f empty.txt
                touch full.txt
                counter=$((counter+1))
                echo "$file is not empty"
            else
                # The file is empty.
                rm -f full.txt
                touch empty.txt
                echo "$file is empty"
              fi
            done
            echo "Counter is $counter"
            done < UserInput.txt
            if ((counter<4))
              then 
                echo "Missing files: Test run cannot start!"
              else
                bash .github/script/getCQ.sh
            fi
        
      - name: Retrive ID and content of input
        run: |
          bash .github/script/getCQ.sh
      
      
    
    
  
