# Action to get which files where changed after a push or a pull request.
name: Get push difference

on: [push, pull_request]

jobs:
  difference:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for changes
        id: diff
        run: |
          if [ $GITHUB_BASE_REF ]; then
            # Pull Request
            git fetch origin $GITHUB_BASE_REF --depth=1
            export DIFF=$( git diff --name-only origin/$GITHUB_BASE_REF $GITHUB_SHA )
            echo "Diff between origin/$GITHUB_BASE_REF and $GITHUB_SHA"
          else
            # Push
            git fetch origin ${{ github.event.before }} --depth=1
            export DIFF=$( git diff --name-only ${{ github.event.before }} $GITHUB_SHA )
            echo "Diff between ${{ github.event.before }} and $GITHUB_SHA"
          fi
          echo "$DIFF"
          # Escape newlines (replace \n with %0A)
          echo "::set-output name=diff::$( echo "$DIFF" | sed ':a;N;$!ba;s/\n/%0A/g' )"
          
      - run: echo "${{ steps.diff.outputs.diff }}"
      
      - run: git diff ${{ github.event.before }} $GITHUB_SHA > CommitChanges.txt
      
      - name: Pull-to-master
        uses: peter-evans/create-pull-request@v3
      
      
      
      
      
      
      
      
      
      
      
      
      
      
