name: Validate CQ

on: push

jobs:
  validate-CQ:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v1
      
      - name: Run JSON validator
        run: |
          cqPath="ontology-network/musical-performance/RecordingProcess/CompetencyQuestions.txt"
          requirements=$(grep -i '[CQ][0-9][0-9]*:\s' $cqPath)
          echo "$requirements" > "requirements.txt"
          while read line; do
            echo "${line//[!0-9]/}"
            if [[ $line =~ :(.+) ]]; then
              strresult=${BASH_REMATCH[1]}
              echo "$strresult"
            else
              echo "unable to parse string $line"
            fi
          done <requirements.txt
