name: Validate CQ

on: push

jobs:
  validate-CQ:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v1
      
      - name: Run CQ validator
        run: |
          echo "$cqPath"
          cqPath="ontology-network/musical-performance/RecordingProcess/CompetencyQuestions.txt"
          cqRequirements=$(grep -i '[CQ][0-9][0-9]*:\s' $cqPath)
          
          echo "$sparqlPath"
          sparqlPath="ontology-network/musical-performance/RecordingProcess/SPARQLQueries.txt"
          sparqlCQRequirements=$(grep -i '[SQCQ][0-9][0-9]*:\s' $sparqlPath)
          
          echo "$erPath"
          erPath="ontology-network/musical-performance/RecordingProcess/ExpectedResults.txt"
          erRequirements=$(grep -i '[ER][0-9][0-9]*:\s' $erPath)
          
          base="https://raw.githubusercontent.com/"
          base1=$(git config --get remote.origin.url | sed 's/.*\/\([^ ]*\/[^.]*\).*/\1/')
          
          echo "$MPbase"
          MPbase="/main/ontology-network/musical-performance/RecordingProcess/RecordingProcess.owl"
          
          echo "$tdbase"
          tdbase="/main/ontology-network/musical-performance/RecordingProcess/SPARQLUnitTest/CQTestData/"
          
          echo "$tcbase"
          tcbase="/main/ontology-network/musical-performance/RecordingProcess/SPARQLUnitTest/CQTestCase/"
          
          echo "$mp"
          mp="$base$base1$MPbase"
          
          echo "$cqtd"
          cqtd="$base$base1$tdbase"
          
          echo "$cqtc"
          cqtc="$base$base1$tcbase"
          
          mpPrefix="@prefix mp: < ${mp} > ."
          tdPrefix="@prefix td: < ${cqtd} > ."
          tcPrefix="@prefix mp: < ${cqtc} > ."
          
          echo '@prefix owlunit: <https://w3id.org/OWLunit/ontology/> . ' > cqTemplate.txt
          echo $mpPrefix >> cqTemplate.txt 
          echo $tdPrefix >> cqTemplate.txt 
          echo $tcPrefix >> cqTemplate.txt 
          echo 'tc:01 a owlunit:CompetencyQuestionVerification ; owlunit:hasCompetencyQuestion "' >> cqTemplate.txt 
          
          echo "$cqRequirements" > "cqRequirements.txt"
          while read line; do
            CQid=${line//[!0-9]/}
            echo "This is the CQid"
            echo $CQid
            if [[ $line =~ :(.+) ]]; then
              CQstrresult=${BASH_REMATCH[1]}
              echo $CQstrresult >> cqTemplate.txt 
              echo ' "; owlunit:hasSPARQLUnitTest " ' >> cqTemplate.txt 
            else
              echo "unable to parse string $line"
            fi
          done <cqRequirements.txt
          
          echo "$sparqlCQRequirements" > "sparqlCQRequirements.txt"
            while read line; do
              SQid=${line//[!0-9]/}
              echo "This is the SQid"
              echo $SQid
              if [[ $line =~ :(.+) ]]; then
                SQstrresult=${BASH_REMATCH[1]}
              fi
            done <sparqlCQRequirements.txt
          
          if [[ $CQid = $SQid ]]; then
            echo $SQstrresult >> cqTemplate.txt 
            cat cqTemplate.txt
          else
            echo "No matching SPARQL query"
          fi
          
        
