name: Construct EP test cases

on: push

jobs:
  validate-EP:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout V2
        uses: actions/checkout@v2
      
      - name: Construct ER test cases
        run: |
          echo "$epPath"
          epPath="ontology-network/musical-performance/RecordingProcess/GeneralConstraints.txt"
          epRequirements=$(grep -i '[IV][0-9][0-9]*:\s' $epPath)
          
          base="https://raw.githubusercontent.com/"
          base1=$(git config --get remote.origin.url | sed 's/.*\/\([^ ]*\/[^.]*\).*/\1/')
          
          echo "$MPbase"
          MPbase="/main/ontology-network/musical-performance/RecordingProcess/RecordingProcess.owl"
          
          echo "$tdbase"
          tdbase="/main/ontology-network/musical-performance/RecordingProcess/ErrorProvocation/ERDataSet/"
          
          echo "$tcbase"
          tcbase="/main/ontology-network/musical-performance/RecordingProcess/ErrorProvocation/ERTestCase/"
          
          echo "$mp"
          mp="$base$base1$MPbase"
          
          echo "$ertd"
          eptd="$base$base1$tdbase"
          
          echo "$ertc"
          eptc="$base$base1$tcbase"
          
          mpPrefix="@prefix mp: < ${mp} > ."
          tdPrefix="@prefix td: < ${eptd} > ."
          tcPrefix="@prefix mp: < ${eptc} > ."
          
          echo '@prefix owlunit: <https://w3id.org/OWLunit/ontology/> . ' > epTemplate.txt
          echo $mpPrefix >> epTemplate.txt 
          echo $tdPrefix >> epTemplate.txt 
          echo $tcPrefix >> epTemplate.txt 
          echo 'tc:01 a owlunit:ErrorProvocation ; owlunit:hasInputData td:EPDataSet.ttl ; owlunit:testsOntology mp: . ' >> epTemplate.txt 
          
          cp epTemplate.txt ontology-network/musical-performance/RecordingProcess/ErrorProvocation/EPTestCase/EPTestCase.ttl
      
      - name: Pull-to-master
        uses: peter-evans/create-pull-request@v3
          
        
