# This is a workflow that is able to create a directory structure, diplay the structure and create a pull request

name: Create directory

on: 
  push: 
    paths: 
      - 'testmanagement/musical-performance/'

jobs:
  # This workflow contains a job called "create directory structure"
  create-directory-structure:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs multiple commands using the runners shell
      - name: Create directory structure for the CC testing
        run: | 
              mkdir CC
              cd CC
              mkdir SPARQLUnitTest
              mkdir IV
              mkdir EP
              echo " This is a list of competency questions " > CQ.txt
              echo " This is a list of general contraints! " > GC.txt
              cd SPARQLUnitTest
              mkdir CQTestCase
              mkdir CQDataSet
              cd CQTestCase 
              echo " This is a new test file! " > CQTestCase.owl
              cd ..
              cd CQDataSet 
              echo " This is a new dataset file! " > CQDataSet.ttl
              cd ..
              cd ..
              cd IV
              mkdir IVTestCase
              mkdir IVDataSet
              cd ..
              cd EP
              mkdir EPTestCase
              mkdir EPDataSet
              
      - name: Display-tree-structure
        run: |
              echo " alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'" " > printTree.zshrc
              tree
              
      - name: Pull-to-master
        uses: peter-evans/create-pull-request@v3
        
        


              
            
        

