# This is a workflow that is able to create directories in Github servers

name: Create directory

on: 
  push

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs multiple commands using the runners shell
      - name: Create directory
        run: | 
              mkdir CC1
              echo " This is a new test file! " > CC1/README.txt
        

