# This is a workflow that is able to create a directory structure, diplay the structure and create a pull request
# Trigger: Commit to the ontology module directory. 
# Input: Preferable the name of the directory that is added
# Output: 1. A directory structure for the testing of the conceptual component that was added. 2. A display of the directory that is added. 3. A pull request to add the directories to the main branch. 


# The name of the directory
name: Create directory

# The event that triggers the action is a commit to the ontology module directory. 
on: 
  push: 
    branches: 
      - main
    paths: 
      - 'ontology-network/musical-performance-ontology/**'
  workflow_dispatch:
  
jobs:
  
  # This workflow contains a job called "create directory structure"
  create-directory-structure:
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps that are executed for this job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      # Create the directory structure for the testing of a Conceptual Component
      - name: Create directory structure for the CC testing
        run: | 
              cd ontology-network
              cd musical-performance-ontology
              mkdir Test
              cd Test
              mkdir SPARQLUnitTest
              mkdir InferenceVerificationTest
              mkdir ErrorProvocationTest
              echo " " > CompetencyQuestions.txt
              echo " " > GeneralConstraints.txt
              echo " " > SPARQLQueries.txt
              echo " " > ExpectedResults.txt
              echo " " > OWLFile.owl
              cd SPARQLUnitTest
              mkdir CQTestCase
              mkdir CQDataSet
              cd CQTestCase 
              echo " " > CQTestCase.owl
              cd ..
              cd CQDataSet 
              echo " " > CQDataSet.ttl
              cd ..
              cd ..
              cd InferenceVerificationTest
              mkdir IVTestCase
              mkdir IVDataSet
              cd IVTestCase
              echo " " > IVTestCase.owl
              cd ..
              cd IVDataSet
              echo " " > IVDataSet.ttl
              cd ..
              cd ..
              cd ErrorProvocationTest
              mkdir EPTestCase
              mkdir EPDataSet
              cd EPTestCase
              echo " " > EPTestCase.owl
              cd ..
              cd EPDataSet
              echo " " > EPDataSet.ttl
              
      # This step displays the structure of the directory that was created in the previous step.      
      - name: Display-tree-structure
        run: |
              echo " alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'" " > printTree.zshrc
              tree
      # This step creates an automatic pull request for the directories that were created.      
      - name: Pull-to-master
        uses: peter-evans/create-pull-request@v3
        
        


              
            
        

