# This is a workflow that is able to find ontology files in the GitHub repository. 
# Trigger: 
# Input: None
# Output: A list of files with .owl or .rdf extensions. 

# The name of the workflow
name: Discover ontology

# The event that triggers the action.
on: 
  workflow_dispatch:
  
jobs:
# This workflow contains a job called "discover"
  discover: 

# The type of runner that the job will run on
    runs-on: ubuntu-latest
    
# Steps that are executed for this job
    steps: 

# Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2


# Gets a list of files with the required extensions
      - name: Run bash script
        run: find . -name '*.owl' -o -name '*.rdf' >> OntologyList.txt
          

# Print txt list   
      - name: Print ontology list
        run: cat OntologyList.txt
        
# Install brew
      - name: Install Brew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        
# install jq package
      - name: Install jq
        run: brew install jq
        
# Create JSON file from txt file
      - name: Create JSON
        run: jq -Rs '[ split("\n")[] | select(length > 0) | split(",") | {OntologyPath:.[0]} ]' OntologyList.txt > OntologyList.json
        
# Print JSON
      - name: Print ontology list in JSON
        run: cat OntologyList.json
# Delete txt file
      - name: Delete txt file
        run: rm OntologyList.txt


      
      
      
    
    
    
      
    
    
    
