name: Validate JSON

on: push

jobs:
  validate-JSON:
    runs-on: ubuntu-latest
    env: 
      JSONValidator: False
      
        
    steps:
      - uses: actions/checkout@v1
      
      - name: Run JSON validator
        run: |
          function JSON_Validator () {
            validator_result="$( PYTHON_ARG="$1" python3 - <<END
          import os
          import json
          import traceback
          str = str(os.environ['PYTHON_ARG'])
          try:
            json.loads(str)
            print("Success!")
          except ValueError as error:
            print(error) 
          END
          )"
            echo $validator_result
          }
          echo "$erPath"
          erPath="ontology-network/musical-performance/RecordingProcess/ExpectedResults.txt"
          erRequirements=$(grep -i '[ER][0-9][0-9]*:\s' $erPath)
          echo "$erRequirements" > "erRequirements.txt"
          while read -r line; do
            if [[ $line =~ :(.+) ]]; then
              ERstrresult=${BASH_REMATCH[1]}
            fi
            
            for i in "${ERstrresult[@]}"
              do
                # remove spaces in the line
                no_whitespace="$(echo -e "${i}" | tr -d '[:space:]')"
                
                # remove string quotations: beginning """ and ending """
                remove_string_quotations=${no_whitespace:3:-3}
                
                evalResult=$(JSON_Validator "$remove_string_quotations")
                echo $evalResult
                
                if [ "$evalResult" = "Success!" ]; then
                  echo "JSONValidator=True" >> $GITHUB_ENV
                else
                  echo "JSONValidator=False" >> $GITHUB_ENV
                fi
            done
          done <erRequirements.txt
          
          echo ${{ env.JSONValidator }}
      
      - name: Run JSON validator
        run: echo ${{ env.JSONValidator }}
  
          #if [ "$valResult" = "Success!" ]; then
          #  echo "JSONValidator=True" >> $GITHUB_ENV
          #else
          #  echo "JSONValidator=False" >> $GITHUB_ENV
          #fi
          
