name: Validate JSON

on: push

jobs:
  validate-JSON:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v1
      
      - name: Run JSON validator
        run: |
          function JSON_Validator () {
            validator_result="$( PYTHON_ARG="$1" python3 - <<END
          import os
          import sys
          import json
          print(os.environ['PYTHON_ARG'])
          
          try:
            json.loads(os.environ['PYTHON_ARG'])
            print("Syntax is correct")
          except ValueError as error:
            print(error) 
            
          END
          )"
          
            echo $validator_result
          }
          
          json='"""{ "head": { "vars": ["recording" ] } , "results": { "bindings": [ {  "recording": { "type":  "uri" ,  "value": "https://raw.githubusercontent.com/YourUsername/YourRepository/main/ontology-network/musical-performance/RecordingProcess/SPARQLUnitTest/CQDataSet/ComeWithMe" } } ] } }"""'
          echo $json
          JSON_Validator "$json"
          
