name: Validate JSON

on: push

jobs:
  validate-SPARQL:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v1
      
      - name: Run JSON validator
        run: |
          function JSON_Validator () {
            validator_result="$( PYTHON_ARG="$1" python3 - <<END
          import os
          import sys
          import json

          try:
            json.loads(os.environ['PYTHON_ARG'])
            print("Syntax is correct")
          except ValueError as error:
            print("There is an error") 
            
          END
          )"
            echo $validator_result
          }
          echo $json
          json='"""{ "head": { "vars": [ "interest" ] }, "results": { "bindings": [{ "interest": { "type": "uri", "value": "https://w3id.org/OWLunit/examples/Basketball" } } ] } }"""'
          JSON_Validator "$json"
