name: Validate JSON

on: push

jobs:
  validate-JSON:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v1
      
      - name: Run JSON validator
        run: |
          function JSON_Validator () {
            validator_result="$( PYTHON_ARG="$1" python3 - <<END
          import os
          import json
          print("test")
          try:
            json.loads(os.environ['PYTHON_ARG'])
            print("Correct!")
          except ValueError as error:
            print(error) 
    
          END
          )"
          echo $validator_result
          }
  
          echo "$erPath"
          erPath="ontology-network/musical-performance/RecordingProcess/ExpectedResults.txt"
          erRequirements=$(grep -i '[ER][0-9][0-9]*:\s' $erPath)
          echo "$erRequirements" > "erRequirements.txt"
          while read -r line; do
            if [[ $line =~ :(.+) ]]; then
              ERstrresult=${BASH_REMATCH[1]}
              valResult=$(JSON_Validator "${ERstrresult[@]}")
              echo $valResult
              if [ "$valResult" = "Success!" ]; then
                echo "JSONValidator=True" >> $GITHUB_ENV
              else
                echo "JSONValidator=False" >> $GITHUB_ENV
              fi
            fi
          done <erRequirements.txt
          
          # valResult=$(JSON_Validator "$ERstrresult")

          # echo $valResult
  
          #if [ "$valResult" = "Success!" ]; then
          #  echo "JSONValidator=True" >> $GITHUB_ENV
          #else
          #  echo "JSONValidator=False" >> $GITHUB_ENV
          #fi
          
