name: Validate JSON

on: push

jobs:
  validate-JSON:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v1
      
      - name: Run JSON validator
        run: |
          function JSON_Validator () {
            echo $1
            validator_result="$( PYTHON_ARG="$1" python3 - <<END
          import os
          import json
          import traceback
          str = str(os.environ['PYTHON_ARG'])
          try:
            json.loads(str)
            print("Correct!")
          except ValueError as error:
            print(error) 
          END
          )"
            echo "Python script result is $validator_result"
          }
          echo "$erPath"
          erPath="ontology-network/musical-performance/RecordingProcess/ExpectedResults.txt"
          erRequirements=$(grep -i '[ER][0-9][0-9]*:\s' $erPath)
          echo "$erRequirements" > "erRequirements.txt"
          while read -r line; do
            if [[ $line =~ :(.+) ]]; then
              ERstrresult=${BASH_REMATCH[1]}
            fi
            
            for i in "${ERstrresult[@]}"
              do
                no_whitespace="$(echo -e "${i}" | tr -d '[:space:]')"
                remove_string_quotations=${no_whitespace:3:-3}
                evalResult=$(JSON_Validator $remove_string_quotations)
                echo "Validation result is $evalResult"
                if [ "$evalResult" = "Success!" ]; then
                  echo "nice"
                else
                  echo "bad" 
                fi
            done
          done <erRequirements.txt
          
          # valResult=$(JSON_Validator "$ERstrresult")

          # echo $valResult
  
          #if [ "$valResult" = "Success!" ]; then
          #  echo "JSONValidator=True" >> $GITHUB_ENV
          #else
          #  echo "JSONValidator=False" >> $GITHUB_ENV
          #fi
          
