# This is a workflow that is able to create temporary urls for the test cases and dataset files.
# Trigger: Input cross check completed successfully. 
# Input: The directory path of a test case or dataset file. 
# Output: Four urls that are needed for a test case: 1. the test case url, 2. the corresponding dataset url, 3. the ontology url, 4. The OWL ontology url.

# The name of the workflow

name: Run testcase

# The event that triggers the action.
on: [push]
 
jobs:

# This workflow contains a job called "test-run"
  run-test:
  
  # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    
    # Check out the repository where the action is going to be executed on.
    steps:
      - name: Checkout V2
        uses: actions/checkout@v2
        
      - name: Setup-JAVA
        uses: actions/setup-java@v2.4.0
        with:
          distribution: 'temurin' 
          java-version: '17'
        
      - name: Setup-OWLUnit
        run: |
            curl -s https://api.github.com/repos/luigi-asprino/owl-unit/releases/latest \
            | grep browser_download_url \
            | cut -d : -f 2,3 \
            | tr -d \" \
            | wget -qi -
      
      - name: Run CQ test
        run: |
            cd ontology-network
            cd musical-performance-ontology
            while read -r line; do
            line="$line"
            cd $line
            done < UserInput.txt
            cd SPARQLUnitTest
            cd CQTestCase
            base="https://raw.githubusercontent.com/FiorelaCiroku/XD-Testing/main/ontology-network/musical-performance-ontology/"
            CQbase="/SPARQLUnitTest/CQTestCase/"
            echo "$CQtestcase"
            CQtestcase="$base$line$CQbase"
            for file in *.owl
            do 
             # echo " The file is $file"
             testcaseURL="$CQtestcase$file"
             echo "Test case URL is $testcaseURL
             cd ..
             cd ..
             cd ..
             cd ..
             cd ..
             java -jar OWLUnit-0.3.2.jar -c $testcaseURL
            done          
     
            

