# This is a workflow that is able to create temporary urls for the test cases and dataset files.
# Trigger: Input cross check completed successfully. 
# Input: The directory path of a test case or dataset file. 
# Output: Four urls that are needed for a test case: 1. the test case url, 2. the corresponding dataset url, 3. the ontology url, 4. The OWL ontology url.

# The name of the workflow

name: Run testcase

# The event that triggers the action.
on: [push]
 
jobs:

# This workflow contains a job called "test-run"
  run-test:
  
  # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    
    # Check out the repository where the action is going to be executed on.
    steps:
      - name: Checkout V2
        uses: actions/checkout@v2
        
      - name: Setup-JAVA
        uses: actions/setup-java@v2.4.0
        with:
          distribution: 'temurin' 
          java-version: '17'
        
      - name: Setup-OWLUnit
        run: |
            curl -s https://api.github.com/repos/luigi-asprino/owl-unit/releases/latest \
            | grep browser_download_url \
            | cut -d : -f 2,3 \
            | tr -d \" \
            | wget -qi -
      
      - name: Run test
        run: |
            java -jar OWLUnit-0.3.2.jar --test-case https://github.com/polifonia-project/musical-performance-ontology/blob/main/test/competency-question/test-case/CQ1.owl

  
