# This is a workflow that is able to run a test case.
# Trigger: A commit to the test case directory. 
# Input: The user input file to get the name of the cc that we are testing. 
# Output: The execution of a test case. 

# The name of the workflow

name: Run testcase

# The event that triggers the action.
on: 
  push: 
    branches: 
      - main
    paths: 
      - 'ontology-network/musical-performance/RecordingProcess/SPARQLUnitTest/CQDataSet/**'
  workflow_dispatch:
 
jobs:

# This workflow contains a job called "test-run"
  run-test:
  
  # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    
    # Check out the repository where the action is going to be executed on.
    steps:
      - name: Checkout V2
        uses: actions/checkout@v2
        
      - name: Setup-JAVA
        uses: actions/setup-java@v2.4.0
        with:
          distribution: 'temurin' 
          java-version: '17'
        
      - name: Setup-OWLUnit
        run: |
            curl -s https://api.github.com/repos/luigi-asprino/owl-unit/releases/latest \
            | grep browser_download_url \
            | cut -d : -f 2,3 \
            | tr -d \" \
            | wget -qi -
      
      - name: Run CQ test
        run: |
            cd ontology-network
            cd musical-performance
            while read -r line; do
            line="$line"
            # echo "CC is $line"
            cd $line
            base="https://raw.githubusercontent.com/"
            base1=$(git config --get remote.origin.url | sed 's/.*\/\([^ ]*\/[^.]*\).*/\1/')
            echo "$base2"
            base2="/main/ontology-network/musical-performance/"
            CQbase="/SPARQLUnitTest/CQTestCase/"
            echo "$CQtestcase"
            CQtestcase="$base$base1$base2$line$CQbase"
            echo "Test case directory url is $CQtestcase"
            cd SPARQLUnitTest
            cd CQTestCase
            for file in *.ttl
            do 
             echo " The file is $file"
             testcaseURL="$CQtestcase$file"
             echo "Test case URL is $testcaseURL"
             cd ..
             cd ..
             cd ..
             cd ..
             cd ..
             java -jar OWLUnit-0.3.2.jar -c $testcaseURL
            done          
            done < UserInput.txt
      
      # This step creates an automatic pull request for the directories that were created.      
      - name: Pull-to-master
        uses: peter-evans/create-pull-request@v3

