name: Setup OWLUnit
on: 
  workflow_dispatch:
  
jobs:    
  setup-OWLUnit: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin' 
        java-version: '17'
    - run: java -cp java HelloWorldApp
      
    - name: Clone OWLUnit github repository
      run: git clone https://github.com/luigi-asprino/owl-unit.git
      
      
      
    
    
    
      
    
    
    
