name: Setup Java
on: 
  push
  
jobs:    
  setup-java: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2.4.0
      with:
        distribution: 'temurin' 
        java-version: '17'


      
      
      
    
    
    
      
    
    
    
