name: Validate SPARQL

on: 
  workflow_dispatch:

jobs:
  validate-SPARQL:
    runs-on: ubuntu-latest
    
    env:
        query: SELECT ?info ?name WHERE { ?person rdfs:seeAlso ?info . ?person foaf:homepage ?name .}
        
    steps:
      - uses: actions/checkout@v1
      
      - name: Install rdflib 
        run: |
          pip install rdflib
      
      - name: Run SPARQL validator
        run: |
          function SPARQL_Validator () {
            validator_result="$( PYTHON_ARG="$1" python3 - <<END
          import os
          import sys
          import rdflib
          from rdflib.plugins.sparql import prepareQuery
          from rdflib.namespace import FOAF
          from rdflib.namespace import RDF
          from rdflib.namespace import RDFS
          from rdflib.namespace import DC
          from rdflib.namespace import OWL
          from rdflib.namespace import XSD
          try:
            q = prepareQuery(os.environ['PYTHON_ARG'], initNs={"foaf": FOAF ,"rdfs": RDFS, "rdf": RDF, "owl": OWL, "xsd": XSD},)
            print("Syntax is correct")
          except Exception as error:
            print(error)
          END
          )"
            echo $validator_result
          }
          SPARQL_Validator "$query"
          
          
          # os.environ['query']
