name: Validate SPARQL

on: push

jobs:
  validate-SPARQL:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Install rdflib 
        run: |
          pip install rdflib
      
      - name: Run SPARQL validator
        run: |
          function SPARQL_Validator {
          python3 - <<END
          import rdflib
          from rdflib.plugins.sparql import prepareQuery
          from rdflib.namespace import FOAF
          from rdflib.namespace import RDF
          from rdflib.namespace import RDFS
          from rdflib.namespace import DC
          from rdflib.namespace import OWL
          from rdflib.namespace import XSD

          def SPARQLValidation(query):
            try:
              q = prepareQuery(query, initNs={"foaf": FOAF ,"rdfs": RDFS, "rdf": RDF, "owl": OWL, "xsd": XSD},)
              return True
    
            except Exception as error:
              print(error)
          
          query = "SELECT ?info ?name WHERE { ?person rdfs:seeAlso ?info . ?person foaf:homepage ?name .}"
          SPARQLValidation(query)
          END
          }
          # Call the python code.
          SPARQL_Validator
