name: Run OWLUnit Tests
on: [push]
 
jobs:
  test-run:
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Checkout V2
        uses: actions/checkout@v2
      
      - run: java -jar OWLUnit-0.3.2.jar -c <URI>       

  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.4.0
        with:
          distribution: 'temurin' 
          java-version: '17'
      - run: git clone https://github.com/luigi-asprino/owl-unit.git

      
