name: Run OWLUnit Tests on Github-Hosted Runner
description: "Run test cases for CQ verification using OWLUnit"
on:
  # Trigger the workflow on push or pull request, but only for the test branch
  push:
    branches:[musical-performance/test/CQ/]
  pull-request: 
    branches:[musical-performance/test/CQ/]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel 
jobs:
 
 # This workflow contains a single job called "test-run"
  test-run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
