name: Validate JSON

on: push

jobs:
  verify-SPARQL-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Run JSON validator
        run: |
          extectedResult="""{ "head": { "vars": [ "interest" ] }, "results": { "bindings": [{ "interest": { "type": "uri", "value": "https://w3id.org/OWLunit/examples/Basketball" } } ] } }"""
          python .github/script/validateJSON.py extectedResult
